# Generated by Django 3.2.4 on 2021-06-13 14:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('choice', models.CharField(max_length=30, verbose_name='Выбор Жилья')),
                ('starting_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Конец')),
                ('total_sum', models.IntegerField(null=True, verbose_name='Сума Оплаты')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('kitchen', models.CharField(blank=True, max_length=20, null=True, verbose_name='Есть ли Кухня')),
                ('washroom', models.IntegerField(blank=True, null=True, verbose_name='Кол. туалетов')),
                ('places', models.IntegerField(verbose_name='Кол. спальных мест')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Кол. комнат')),
                ('pool', models.CharField(blank=True, max_length=20, verbose_name='Есть ли бильярд')),
                ('img', models.ImageField(upload_to='photos/rooms/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='photos/rooms/')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
